schema_version: 1
parent: species
animal:
  movement_speed: 1.0
  energy_consumption: 1
  hunting_range: 5.0
  hunting_success_rate: 0.5
  detection_range: 500.0
  food_types: []
  hunting_cooldown_duration: 0
  min_reproduction_age: 0
  reproduction_cooldown: 0
  eating_range: 0.0
  satisfied_threshold_ratio: 0.8
  starving_threshold_ratio: 0.2
  wandering_duration: 50
  wander_radius: 40.0
  energy_efficiency: 1.0
  use_bt: false
  mating_duration: 5      
  pregnancy_duration: 100  
  mating_range: 5.0        
  pregnancy_speed_penalty: 0.5
  mating_desire_probability: 0.6
  # 被击杀后提供的基础营养（与当前能量脱钩）
  nutrition_value: 100.0
  # 饥饿伤害与周期配置
  starvation_damage: 1.0
  starvation_damage_interval_ratio: 0.25
  # energy加成 ~ https://doi.org/10.1093/conphys/coac083
  # 加成公式 = nutrition_bonus_max * pow(prey.energy / prey.max_energy, nutrition_bonus_curve_alpha)
  # 最终获得能量 gained_energy = (prey.nutrition_value + bonus) * predator.energy_efficiency
  nutrition_bonus_max: 1.0 # 1.0就相当于最多获得猎物当前的power1倍
  nutrition_bonus_curve_alpha: 1.0 # 1.0就相当于线性获得猎物当前的power
  # HP恢复基础值
  hp_regen_base_per_day: 5.0
  # HP恢复的状态加成：
  hp_regen_mul_satisfied: 2.0
  hp_regen_mul_normal: 1.0
  hp_regen_mul_starving: 0.25
  # HP恢复周期（0-1天）
  regan_interval_ratio: 0.25
